controller_list:
  - name: left_arm_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory      # JointTrajectoryController   FollowJointTrajectory
    joints:
      - linear_x_actuator_joint
      - linear_z_actuator_joint
      - linear_y1_actuator_joint
      - linear_y2_actuator_joint
      - cam1_actuator_joint
      - cam2_actuator_joint
