# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rokos_left_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - linear_x_actuator_joint
    - linear_z_actuator_joint
    - linear_y1_actuator_joint
    - linear_y2_actuator_joint
    - cam1_actuator_joint
    - cam2_actuator_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - linear_x_actuator_joint
    - linear_z_actuator_joint
    - linear_y1_actuator_joint
    - linear_y2_actuator_joint
    - cam1_actuator_joint
    - cam2_actuator_joint
  gains:
    linear_x_actuator_joint:
      p: 250 # 950  ---- 500
      d: 15000 # 100 ----- 1000
      i: 2 # 1 # 2 ----- 0
      i_clamp: 1
    linear_z_actuator_joint:
      p: 100000
      d: 1000
      i: 1000
      i_clamp_max: 200
      i_clamp_min: 0
    linear_y1_actuator_joint:
      p: 3500 # 900
      d: 1000 # 150
      i: 0 # 0
      i_clamp: 1
    linear_y2_actuator_joint:
      p: 3500 # 900
      d: 1000 # 150
      i: 0 # 0
      i_clamp: 1
    cam1_actuator_joint:
      p: 5000
      d: 90
      i: 1
      i_clamp: 1
    cam2_actuator_joint:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
